build-settings: &build-settings
  machine: true
  working_directory: ~/dockcross

version: 2.1
jobs:
  base:
    <<: *build-settings
    steps:
      - checkout
      - run:
         name: base build
         command: |
           docker pull debian:buster
           make base
           mkdir -p ~/docker
           docker save -o ~/docker/base.tar debian:buster dockcross/base:latest
      - run:
         name: base test
         command: |
           make base.test
      - save_cache:
          key: base-assets-{{ .Revision }}
          paths:
            - ~/docker/base.tar
            - ~/dockcross
  moxiebox-moxie:
    <<: *build-settings
    steps:
      - restore_cache:
          key: base-assets-{{ .Revision }}
      - run:
         name: moxiebox-moxie build
         no_output_timeout: 1.5h
         command: |
           docker load -i ~/docker/base.tar
           make moxiebox-moxie
           tagged=$(docker images -q -f 'since=dockcross/moxiebox-moxie:latest' --format '{{.Repository}}:{{.Tag}}' | grep moxiebox-moxie)
           docker save -o ~/docker/moxiebox-moxie.tar dockcross/moxiebox-moxie:latest $tagged
      - run:
         name: moxiebox-moxie test
         command: |
           make moxiebox-moxie.test
      - save_cache:
          key: moxiebox-moxie-assets-{{ .Revision }}
          paths: ~/docker/moxiebox-moxie.tar
  deploy:
    <<: *build-settings
    steps:
      - restore_cache:
          key: moxiebox-moxie-assets-{{ .Revision }}
      - deploy:
          name: Deploy moxiebox-moxie
          command: |
            docker load -i ~/docker/moxiebox-moxie.tar
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag dockcross/moxiebox-moxie:latest ledgerhq/moxiebox-moxie:latest
            docker push ledgerhq/moxiebox-moxie:latest
            tagged=$(docker images -q -f 'since=dockcross/moxiebox-moxie:latest' --format '{{.Repository}}:{{.Tag}}' | grep moxiebox-moxie|sed 's#dockcross/##g')
            docker tag "dockcross/${tagged}" "ledgerhq/${tagged}"
            docker push "ledgerhq/${tagged}"

workflows:
    version: 2.1
    build-test-deploy:
      jobs:
        - base
        - moxiebox-moxie:
            requires:
              - base
        - deploy:
            requires:
              - base
              - moxiebox-moxie
            filters:
              branches:
                only:
                  - master
              tags:
                only: /.*/
